[Log] Object (nhlCities.js, line 277)

Anaheim Ducks: ["Mitch Callahan", "Rocco Grimaldi", "Ian McCoshen", "Chad Ruhwedel", "Jason Zucker"] (5)

Arizona Coyotes: ["Sean Couturier", "Trevor Lewis", "Matthew Tkachuk", "Auston Matthews"] (4)

Boston Bruins: Array (31)
0 "Nick Bonino"
1 "Noel Acciari"
2 "Noah Hanifin"
3 "Keith Yandle"
4 "Paul Carey"
5 "Colin White"
6 "Jimmy Hayes"
7 "Jimmy Vesey"
8 "John Carlson"
9 "Brian Boyle"
10 "Charlie Coyle"
11 "Mark Fayne"
12 "Jack Eichel"
13 "Brian Dumoulin"
14 "Garnet Hathaway"
15 "Brian Flynn"
16 "Ron Hainsey"
17 "Chris Kreider"
18 "Bobby Farnham"
19 "Ben Lovejoy"
20 "Kevin Hayes"
21 "Matt Grzelcyk"
22 "Conor Sheary"
23 "Zach Sanford"
24 "Tim Schaller"
25 "David Warsofsky"
26 "Brian Strait"
27 "Mike Vecchione"
28 "Frank Vatrano"
29 "Paul Thompson"
30 "Chris Wagner"

Array Prototype

Buffalo Sabres: Array (15)
0 "Justin Bailey"
1 "Patrick Kane"
2 "Miles Wood"
3 "Sean Malone"
4 "Marcus Foligno"
5 "Nick Foligno"
6 "Dustin Brown"
7 "Shane Prince"
8 "Ryan Callahan"
9 "Brian Gionta"
10 "Stephen Gionta"
11 "Adam Clendening"
12 "Alex Tuch"
13 "Cristoval Nieves"
14 "Lee Stempniak"

Array Prototype

Calgary Flames: Array (31)
0 "Jay Beagle"
1 "Mike Green"
2 "Patrick Eaves"
3 "Josh Morrissey"
4 "Alex Nylander"
5 "Ty Rattie"
6 "Joe Colborne"
7 "Thomas Hickey"
8 "Taylor Hall"
9 "Justin Dowling"
10 "Hunter Shinkaruk"
11 "Brayden Point"
12 "William Nylander"
13 "Derek Dorsett"
14 "Kris Versteeg"
15 "Brandon Davidson"
16 "Braydon Coburn"
17 "Cody Franson"
18 "Shea Weber"
19 "Derek Ryan"
20 "Tyler Johnson"
21 "Connor Jones"
22 "Patrick Marleau"
23 "Curtis McKenzie"
24 "Brayden McNabb"
25 "Mason Raymond"
26 "Paul Postma"
27 "Colton Sceviour"
28 "Kris Russell"
29 "Devin Setoguchi"
30 "Zack Smith"

Array Prototype

Carolina Hurricanes: ["Jared Boll", "Ben Smith"] (2)

Chicago Blackhawks: Array (30)
0 "Justin Abdelkader"
1 "Vinnie Hinostroza"
2 "Christian Fischer"
3 "Mike Reilly"
4 "John Hayden"
5 "T.J. Tynan"
6 "Connor Carrick"
7 "J.T. Compher"
8 "Hudson Fasching"
9 "Drew Stafford"
10 "Alex Galchenyuk"
11 "Christian Dvorak"
12 "Kevin Gravel"
13 "Ryan Dzingel"
14 "Jordan Schmaltz"
15 "Craig Smith"
16 "Phil Kessel"
17 "Ryan Suter"
18 "Nick Schmaltz"
19 "Jack Skille"
20 "Nick Lappin"
21 "Josh Manson"
22 "Max McCormick"
23 "Tanner Kero"
24 "Luke Glendening"
25 "John Moore"
26 "Robbie Russo"
27 "Zach Redmond"
28 "Tommy Wingels"
29 "Luke Witkowski"

Array Prototype

Colorado Avalanche: ["Brandon Carlo", "Nick Shore", "Jaccob Slavin", "Drew Shore"] (4)

Columbus Blue Jackets: ["Jack Johnson", "John-Michael Liles", "Connor Murphy", "Sean Kuraly", "Jack Roslovic"] (5)

Dallas Stars: ["Stefan Noesen", "Blake Coleman", "Seth Jones", "Nicolas Kerdiles", "Tyler Myers", "Jon Merrill"] (6)

Detroit Red Wings: Array (37)
0 "Reid Boucher"
1 "Patrick Brown"
2 "T.J. Brodie"
3 "Erik Condra"
4 "Andy Greene"
5 "Austin Watson"
6 "Steven Kampfer"
7 "Andrew Copp"
8 "Ian Cole"
9 "Jeff Petry"
10 "Aaron Ekblad"
11 "Cam Fowler"
12 "Zack Kassian"
13 "Matt Martin"
14 "Matt Beleskey"
15 "Matt Puempel"
16 "Austin Czarnik"
17 "Kevin Porter"
18 "Danny DeKeyser"
19 "Kyle Connor"
20 "Seth Griffith"
21 "Matt Greene"
22 "Matt Hunwick"
23 "Ryan Kesler"
24 "Torey Krug"
25 "Dylan Larkin"
26 "Alec Martinez"
27 "Jordan Oesterle"
28 "Zach Werenski"
29 "Michael McCarron"
30 "Steve Oleksy"
31 "Dalton Prout"
32 "Blake Pietila"
33 "Greg Pateryn"
34 "Bryan Rust"
35 "Corey Tropp"
36 "Jacob Trouba"

Array Prototype

Edmonton Oilers: Array (48)
0 "Jarome Iginla"
1 "Joe Morrow"
2 "Johnny Boychuk"
3 "Matthew Benning"
4 "Kevin Connauton"
5 "Brendan Guhle"
6 "Jared Spurgeon"
7 "Duncan Siemens"
8 "Vernon Fiddler"
9 "Brett Kulak"
10 "David Schlemko"
11 "Bryan Little"
12 "Ryan Garbutt"
13 "John Quenneville"
14 "Alex Petrovic"
15 "Tyler Ennis"
16 "Taylor Fedun"
17 "Brendan Gallagher"
18 "Dion Phaneuf"
19 "Deryk Engelland"
20 "Jay Bouwmeester"
21 "Dillon Simpson"
22 "Jason Chimera"
23 "Lance Bouma"
24 "Daniel Carr"
25 "Mark Pysyk"
26 "Rene Bourque"
27 "Kyle Brodziak"
28 "Shane Doan"
29 "Blake Comeau"
30 "Dwight King"
31 "Adam Cracknell"
32 "Nelson Nogier"
33 "Luke Schenn"
34 "Taylor Leier"
35 "Brayden Schenn"
36 "Eric Gryba"
37 "Chandler Stephenson"
38 "Boyd Gordon"
39 "Mark Letestu"
40 "Clarke MacArthur"
41 "Colton Parayko"
42 "Nick Holden"
43 "Tyson Jost"
44 "Carter Rowney"
45 "Karl Stollery"
46 "Scottie Upshall"
47 "Linden Vey"

Array Prototype

Florida Panthers: ["Jakob Chychrun", "Shayne Gostisbehere", "Jaycob Megna"] (3)

Las Vegas Golden Knights: [] (0)

Los Angeles Kings: ["Beau Bennett", "Emerson Etem", "Matt Nieto", "Shane Harper", "Kevan Miller"] (5)

Minnesota Wild: Array (41)
0 "David Backes"
1 "Nick Bjugstad"
2 "Matt Tennyson"
3 "Zach Parise"
4 "Paul Martin"
5 "Tyler Pitlick"
6 "Justin Braun"
7 "Joseph Labate"
8 "J.T. Brown"
9 "Brock Boeser"
10 "Seth Helgeson"
11 "Matt Niskanen"
12 "Matt Cullen"
13 "Jonny Brodzinski"
14 "Derek Forbort"
15 "Matt Hendricks"
16 "Erik Johnson"
17 "Tom Gilbert"
18 "Alex Goligoski"
19 "Jake Gardiner"
20 "Jake Guentzel"
21 "Michael Kapla"
22 "Jake McCabe"
23 "Anders Lee"
24 "Jamie McBain"
25 "Justin Faulk"
26 "Kyle Okposo"
27 "Nick Jensen"
28 "Ryan McDonagh"
29 "Nick Leddy"
30 "Kyle Rau"
31 "Joe Pavelski"
32 "Jordan Schroeder"
33 "Brady Skjei"
34 "Nate Prosser"
35 "Mark Stuart"
36 "Derek Stepan"
37 "Nate Schmidt"
38 "C.J. Smith"
39 "Chris VandeVelde"
40 "Blake Wheeler"

Array Prototype

Montreal Canadiens: Array (56)
0 "Sidney Crosby"
1 "Patrice Bergeron"
2 "Anthony Beauvillier"
3 "Gabriel Bourque"
4 "Alex Burrows"
5 "Alex Chiasson"
6 "Marc-Edouard Vlasic"
7 "Mark Barberio"
8 "Marco Scandella"
9 "Alex Biega"
10 "Mike Ribeiro"
11 "Kris Letang"
12 "Francois Beauchemin"
13 "Phillip Danault"
14 "David Desharnais"
15 "Yanni Gourde"
16 "Thomas Chabot"
17 "Michael Bournival"
18 "Jean-Sebastien Dea"
19 "Simon Despres"
20 "Alex Grenier"
21 "Alex Carrier"
22 "Paul Stastny"
23 "Jonathan Drouin"
24 "Michael Chaput"
25 "Nicolas Deslauriers"
26 "William Carrier"
27 "Jason Demers"
28 "Laurent Dauphin"
29 "Jason Pominville"
30 "Anthony Duclair"
31 "Michael Matheson"
32 "Frederik Gauthier"
33 "Frederick Gaudreau"
34 "A.J. Greer"
35 "Gabriel Dumont"
36 "Charles Hudon"
37 "Liam O'Brien"
38 "Alex Killorn"
39 "Brad Marchand"
40 "Nathan MacKinnon"
41 "Andrew MacDonald"
42 "Jonathan Marchessault"
43 "Jonathan Huberdeau"
44 "Anthony Mantha"
45 "Steve Ott"
46 "Adam Pardy"
47 "Adam Mcquaid"
48 "Mathieu Perreault"
49 "Cedric Paquette"
50 "Teddy Purcell"
51 "Samuel Morin"
52 "Torrey Mitchell"
53 "David Savard"
54 "Logan Shaw"
55 "Antoine Vermette"

Array Prototype

Nashville Predators: ["Nic Dowd"] (1)

New Jersey Devils: ["Kenny Agostino", "Drew Miller", "Trevor van Riemsdyk", "James van Riemsdyk"] (4)

New York Islanders: ["Anthony Bitetto", "Patrick Cannone", "Kevin Labanc", "Rob O'Gara", "Sonny Milano"] (5)

New York Rangers: ["Cam Atkinson", "Adam Erne", "Brian Lashoff", "Colin McDonald", "Brett Pesce", "Max Pacioretty", "Kevin Shattenkirk", "Steven Santini", "Brandon Sutter", "Colin Wilson"] (10)

Ottawa Senators: Array (23)
0 "Zach Bogosian"
1 "Trevor Smith"
2 "Mackenzie Weegar"
3 "Jean-Gabriel Pageau"
4 "Cody Ceci"
5 "Paul Byron"
6 "Marc Methot"
7 "Nicholas Baptiste"
8 "Erik Gudbranson"
9 "Ryan Spooner"
10 "Mark Borowiecki"
11 "Jay McClement"
12 "Scott Harrington"
13 "Derick Brassard"
14 "PA Parenteau"
15 "Calvin de Haan"
16 "Remi Elie"
17 "Eric Gelinas"
18 "Ben Hutton"
19 "Slater Koekkoek"
20 "Samuel Henley"
21 "Matthew Peca"
22 "Wade Megan"

Array Prototype

Philadelphia Flyers: ["Erik Burgdoerfer", "Anthony Deangelo", "Johnny Gaudreau", "Buddy Robinson", "Bobby Ryan", "Tom Sestito", "Michael Zalewski"] (7)

Pittsburgh Penguins: ["Vincent Trocheck", "Brandon Saad", "Matt Bartkowski", "Riley Barber", "Stephen Johns"] (5)

San Jose Sharks: ["Casey Bailey", "Matt Carle", "Nate Thompson", "Brandon Dubinsky", "Brooks Orpik"] (5)

St. Louis Blues: ["Chris Butler", "Adam Lowry", "Chris Wideman", "Patrick Maroon", "Scott Mayfield", "Clayton Keller"] (6)

Tampa Bay Lightning: ["Ryan Carpenter", "Ryan Hartman"] (2)

Toronto Maple Leafs: Array (154)
0 "Josh Anderson"
1 "Cory Conacher"
2 "Josh Jooris"
3 "Jeff Carter"
4 "Nazem Kadri"
5 "Drew Doughty"
6 "Sam Gagner"
7 "Bo Horvat"
8 "Dylan Demelo"
9 "Andreas Athanasiou"
10 "Travis Konecny"
11 "Joe Thornton"
12 "Tyler Bertuzzi"
13 "Derek MacKenzie"
14 "Cameron Gaunce"
15 "Brendan Gaunce"
16 "Ryan Johnston"
17 "Chris Tanev"
18 "Andrew Cogliano"
19 "Freddie Hamilton"
20 "Gemel Smith"
21 "Adam Pelech"
22 "Jason Spezza"
23 "Peter Holland"
24 "Barclay Goodrow"
25 "Mike Blunden"
26 "Brandon Tanev"
27 "Mike Liambas"
28 "Dougie Hamilton"
29 "Mike Cammalleri"
30 "Joshua Ho-Sang"
31 "Evan Rodrigues"
32 "Harry Zolnierczyk"
33 "Luke Gazdic"
34 "P.K. Subban"
35 "Reilly Smith"
36 "Daniel Winnik"
37 "Jamie Oleksiak"
38 "Chris Stewart"
39 "Tom Wilson"
40 "Trevor Daley"
41 "Mark Giordano"
42 "Jeff Skinner"
43 "Brandon Pirri"
44 "Cal O'Reilly"
45 "Phillip Di Giuseppe"
46 "Casey Cizikas"
47 "Connor Brown"
48 "Joseph Cramarossa"
49 "Zach Hyman"
50 "Chris Didomenico"
51 "Chris Kelly"
52 "Frank Corrado"
53 "Brady Austin"
54 "Spencer Abbott"
55 "Evan McEneny"
56 "Ryan Ellis"
57 "Tyler Gaudet"
58 "Ben Harpur"
59 "Darnell Nurse"
60 "Mark Jankowski"
61 "Ben Chiarot"
62 "Andy Andreoff"
63 "Dan Renouf"
64 "Drake Caggiula"
65 "Taylor Beck"
66 "Riley Sheahan"
67 "Brent Burns"
68 "Kevin Bieksa"
69 "Nathan Beaulieu"
70 "Brian Campbell"
71 "Cody Bass"
72 "Alan Quine"
73 "Andrew Shaw"
74 "Nick Cousins"
75 "Brad Richardson"
76 "Lawson Crouse"
77 "Kyle Clifford"
78 "Dan Girardi"
79 "Cal Clutterbuck"
80 "Tanner Richard"
81 "Steven Stamkos"
82 "Joseph Blandisi"
83 "Mitchell Marner"
84 "Sam Bennett"
85 "Logan Couture"
86 "Micheal Haley"
87 "Zac Dalpe"
88 "Michael Del Zotto"
89 "Andrew Desjardins"
90 "Jason Dickinson"
91 "Jake Dotchin"
92 "Bryan Bickell"
93 "Josh Bailey"
94 "Matt Stajan"
95 "Nick Paul"
96 "Robby Fabbri"
97 "Ryan Sproul"
98 "John Tavares"
99 "Cody Goloubef"

Array Prototype

Vancouver Canucks: Array (40)
0 "Matt Irwin"
1 "Tyson Barrie"
2 "Jordie Benn"
3 "Jamie Benn"
4 "Milan Lucic"
5 "Ryan Johansen"
6 "Evander Kane"
7 "Troy Brouwer"
8 "Morgan Rielly"
9 "Ben Street"
10 "Mathew Barzal"
11 "Karl Alzner"
12 "Patrick Wiercioch"
13 "Ryan Nugent-Hopkins"
14 "Tyler Wotherspoon"
15 "Josh Gorges"
16 "Justin Schultz"
17 "Brenden Dillon"
18 "Kyle Turris"
19 "Jake Virtanen"
20 "Brett Connolly"
21 "Dan Hamhuis"
22 "Jason Garrison"
23 "Derek Grant"
24 "Andrew Ladd"
25 "Brad Hunt"
26 "Shea Theodore"
27 "Mark McNeill"
28 "Danton Heinen"
29 "Brandon Manning"
30 "Jordan Weal"
31 "Colton Sissons"
32 "Bracken Kearns"
33 "Curtis Lazar"
34 "Jujhar Khaira"
35 "T.J. Oshie"
36 "Nic Petan"
37 "Troy Stecher"
38 "Brent Seabrook"
39 "Clayton Stoner"

Array Prototype

Washington Capitals: [] (0)

Winnipeg Jets: Array (51)
0 "Alex Steen"
1 "Jonathan Toews"
2 "Duncan Keith"
3 "Ryan Reaves"
4 "Quinton Howden"
5 "Mark Stone"
6 "Travis Zajac"
7 "Dale Weise"
8 "Dylan McIlrath"
9 "Brett Lernout"
10 "Max Domi"
11 "Cody Eakin"
12 "Patrick Sharp"
13 "Michael Stone"
14 "Josh Archibald"
15 "Ryan Murray"
16 "Matt Dumba"
17 "Tyler Bozak"
18 "Scott Hartnell"
19 "Chris Kunitz"
20 "Jordan Eberle"
21 "Garrett Mitchell"
22 "Ryan Getzlaf"
23 "Tanner Glass"
24 "Jordan Staal"
25 "Robert Bortuzzo"
26 "Tom Pyatt"
27 "Taylor Chorney"
28 "Marc Staal"
29 "Eric Staal"
30 "Dustin Byfuglien"
31 "Aaron Ness"
32 "Matt Calvert"
33 "Jordan Martinook"
34 "Joel Edmundson"
35 "Ryan White"
36 "Justin Falk"
37 "Eric Fehr"
38 "Byron Froese"
39 "Micheal Ferland"
40 "Darren Helm"
41 "Travis Hamonic"
42 "Cody McLeod"
43 "Paul Ladue"
44 "Brock Nelson"
45 "Nick Schultz"
46 "Jaden Schwartz"
47 "Derrick Pouliot"
48 "Ryan Pulock"
49 "Damon Severson"
50 "Jordin Tootoo"

Array Prototype

Object Prototype
